name: Deploy to VPS
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and deploy
        id: action-ssh
        uses: tiyee/action-ssh@1.0.1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          privateKey: ${{ secrets.SSH_KEY }}
          command: 'cd /var/www/html/kairo.iru.codes && git pull && composer install && pnpm i && pnpm build'
